### ISSUE TITLE
stisknutí více kláves najednou

### ISSUE THREAD

**Issue by x0nix** [mimatik/shadowkeep#12]
Nápad: co to prostě udělat tak, že když se zmáčkne více kláves najednou, nestane se nic?
Hra je tahová, pohyb myslím dovolíme jen ortogonální. Pak by to imo dávalo smysl.

Stačilo by jednoduše:
```
        if sum(pressed_keys) > 1:
            return

```
(pressed_keys je seznam všech kláves v daném pořadí 0 nestisknuto, 1 stisknuto)

**Comment by mimatik** [comment]
super napad!
